source 'https://rubygems.org'

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, and run `bundle update`.

gem "jekyll"

# This is the theme you have chosen if you relative to the GitHub Pages theme gem
# gem "jekyll-theme-cayman"

# For GitHub Pages
gem "github-pages", group: :jekyll_plugins

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
